### ISSUE TITLE
The readme has the wrong username and  password for the vulnerable linux vm

### ISSUE THREAD

**Issue by goldenstandard1** [sagishahar/lpeworkshop#1]
The readme says that username is password321 and the password is password123:
"Lab VM for Linux Exercises (user:password321, root:password123)"
The username is actually user, and the password is password321.

**Comment by sagishahar** [comment]
Thanks for your feedback. I was under the impression that it is clear but it seems not to be the case. I have updated the information hoping it will be clearer.
